### ISSUE TITLE
Incorrect version reported as latest

### ISSUE THREAD

**Issue by toptensoftware** [loic-sharma/BaGet#117]
BaGet seems to report the incorrect version number as the latest version:

eg: here's the main home page showing build 168 as the latest:

![image](https://user-images.githubusercontent.com/179862/48038884-b0283780-e1c6-11e8-9255-a15b1836c297.png)

but when I click on it, 172 is really the latest:

![image](https://user-images.githubusercontent.com/179862/48038908-d0f08d00-e1c6-11e8-9885-93b0245d51b7.png)

The "Manage NuGet Packages" command in Visual Studio also shows the incorrect latest version.

Also, the last updated time stamp says 11 hours ago, but this was just uploaded 10 mins ago.

Restarting the server didn't help.   Pulling latest version of BaGet didn't help.

Could this be something about the way the package is authored confusing BaGet?

Brad

**Comment by toptensoftware** [comment]
When I search on the home page by name I get the correct version:

![image](https://user-images.githubusercontent.com/179862/48039457-f7172c80-e1c8-11e8-9fb3-918ba862b0d5.png)

**Comment by toptensoftware** [comment]
I've hacked this by changing this line:

https://github.com/loic-sharma/BaGet/blob/e9ebce2bd390796f266a747db40619095750249c/src/BaGet.Core/Services/DatabaseSearchService.cs#L35

to

~~~
.OrderByDescending(p => p.Version)
~~~

**Comment by loic-sharma** [comment]
Thanks for reporting this. This is a known issue with BaGet's database search that is surprisingly tricky to fix. The underlying problem is that ordering database records using [Semantic Versioning 2](https://semver.org/) is very difficult. Right now, BaGet's database search just grabs the first 20 packages it can find and returns that as the search results. This is likely incorrect if there are more than 20 packages in the database.

I think the best way to fix this is to store a "search result" record for each package in the database. This record will contain the package's id and its latest version. Each time a new version is uploaded, its corresponding "search result" record should be updated.

**Comment by toptensoftware** [comment]
Thanks for that.  I've pulled down your change and it seems to be working correctly now.

Perhaps the semver stuff would be easier if the db stored each version component separately, or normalized it someway so that normal string comparisons work.  eg: 00000.00001.00002

**Comment by loic-sharma** [comment]
Great, I’ll close this issue off then!

That approach works for semver 1 which had a fixed number of fields, but semver 2 allows for arbitrarily deep version fields. For example, 1.0.0-0 has a lower precedence than 1.0.0-0.0 in semver 2. This is really hard to calculate in a database.
