### ISSUE TITLE
[Client SDK] Test performance on large static feeds

### ISSUE THREAD

**Issue by loic-sharma** [loic-sharma/BaGet#304]
### Is your feature request related to a problem? Please describe.
[Sleet](https://github.com/emgarten/Sleet) creates large static feeds that require high performance from client libraries.

Example JSON feed: JSON feed: https://dotnetfeed.blob.core.windows.net/dotnet-core/search/query?q=&skip=0&take=15&prerelease=false&semVerLevel=2.0.0 (141 MB, raw, without gzip etc)
See: https://github.com/NuGetPackageExplorer/NuGetPackageExplorer/issues/804

### Describe the solution you'd like
Verify the performance of BaGet's NuGet SDK libraries are acceptable. Consider moving to `System.Text.Json` if necessary (this would help remove the Newtonsoft.Json dependency)

**Comment by 304NotModified** [comment]
FYI, haven't tested System.Text.Json (due to the special converters), but skipping just parsing it intermediate to List with Json.Net (instead by JObject), saves almost 50%

![image](https://user-images.githubusercontent.com/5808377/62902187-27df5000-bd5f-11e9-8caa-6ad89ed2a820.png)


See https://github.com/NuGetPackageExplorer/NuGetPackageExplorer/issues/804#issuecomment-520614388

**Comment by loic-sharma** [comment]
I verified that my results aligned to this: https://github.com/NuGetPackageExplorer/NuGetPackageExplorer/issues/804#issuecomment-520614388
