### ISSUE TITLE
Is BaGet ready for production?

### ISSUE THREAD

**Issue by tinohager** [loic-sharma/BaGet#319]
Is there already an official release? I only found prereleases.

Thanks

**Comment by loic-sharma** [comment]
Hello, thanks for opening this issue! First, let me note that I recommend using BaGet for scenarios where packages are public or BaGet is firewalled from the internet. Otherwise, I would recommend using something like Azure Artifacts. BaGet is prerelease for semantic versioning reasons: I haven't settled on a stable API surface yet, and I'd like to avoid bumping the major version constantly. Please let me know if you have any questions, or if you have any suggestions!
