### ISSUE TITLE
Rename "BaGet.Core.Server" to "BaGet.AspNetCore"

### ISSUE THREAD

**Issue by loic-sharma** [loic-sharma/BaGet#344]
Also improve description "Controllers and routing" etc..

This blocks https://github.com/loic-sharma/BaGet/issues/396

**Comment by loic-sharma** [comment]
Hi @michael-baker, thank you for your reply!

> Renaming projects is something that makes merging unfun. Unless there is a really compelling reason to rename the project could you consider leaving it as it stands today?

That makes sense, and I apologize for the churn this will introduce. I'd like to make it easy to add BaGet to an existing ASP.NET Core project. This will let advanced customers like you customize BaGet to their hearts desire (Want to set HSTS headers? Want to read configs from Azure Key Vault?). I will need to do some breaking changes to enable this experience. I hope that makes sense, but please let me know if you have any feedback!

I'd like to reach BaGet v1 "soon"-ish, at which point I will lock down BaGet's public APIs.

> I have vendored this excellent project into my own code base and extended with some bits and bobs that is needed to service internal enterprise environments.

What kind of extensions have you added to BaGet? Is there anything you'd like me to add to BaGet directly?

**Comment by michael-baker** [comment]
I don't believe my modifications are general purpose enough to warrant inclusion in the core product. 

I realize I could add these features with a front end, gateway and a million other ways but I decided to just modify the projects directly.

I added support for 
- Certificate authentication.
- Azure Active directory authentication
- Serving the package content directly from the storage server (in my case Azure blob) rather than via the web front end. This lets me route clients to the closest blob storage server in Azure. I could not get the Azure CDN to do what I wanted so I built my own poor mans CDN.

**Comment by loic-sharma** [comment]
Wow that's impressive.

> * Certificate authentication.
> * Azure Active directory authentication

Did you add a NuGet client authentication plugin to support these? Why do you need both certificate authentication and Azure Active Directory?

> * Serving the package content directly from the storage server (in my case Azure blob) rather than via the web front end. This lets me route clients to the closest blob storage server in Azure. I could not get the Azure CDN to do what I wanted so I built my own poor mans CDN.

How do you route clients - does the web front end redirect to the correct blob storage?

How do you keep all your blob storage accounts up-to-date?

I'd love to learn more about your scenario! Would you be up to chat on Skype or something? :)

**Comment by loic-sharma** [comment]
Addressed in https://github.com/loic-sharma/BaGet/pull/678
