### ISSUE TITLE
Order packages by version

### ISSUE THREAD

**Issue by ismcagdas** [loic-sharma/BaGet#348]
### Is your feature request related to a problem? Please describe.
I want to sort packages in my query by version number descending but for some cases I can't do that. Let's say that I have a package with version `101.0.0.0` and `11.0.0.0`. If I use NormalizedVersionString or OriginalVersionString, it results like below:

![image](https://user-images.githubusercontent.com/4133525/65409679-0018e880-ddf1-11e9-8857-f45c7e5bfdbc.png)

### Describe the solution you'd like
It would be good to have an integer field for VersionNumber like 1000*MajorVersion+100*MinorVersion etc... Or having 4 fields (MajorVersion, MinorVersion, etc...) would be better.

### Describe alternatives you've considered
I can clone the source code BaGet and add those fields but I would prefer to hear your suggestion first.

By the way, using `OrderByDescending(e=> e.Version.Major)` was working before but since EF Core 3.0 disabled client side query execution, it is not useful anymore.

Thanks.

**Comment by loic-sharma** [comment]
Out of curiosity, what's your scenario? Can you instead grab all versions for the database, and order them in memory using `NuGetVersion`?

Ordering versions in a database is **hard** due to [SemVer 2.0.0 precedence rules on the pre-release label](https://semver.org/#spec-item-11). Sadly it isn't as easy as adding `Major,` `Minor`, `Patch`, and `PreReleaseLabel` fields. For proper SemVer 2.0.0 support, you need to support pre-release labels with multiple fields like `1.0.0-prerelease.fields.here.have.precedence`. I have a prototype where I generated a string whose lex ordering tries to preserve SemVer2 ordering. For example:

Version | Result (preserves lex ordering)
-------- | ----------------------------------
1.0.0     | 0001000000r
1.0.0-abc |  0001000000pabc0000000

This prototype had limitations and couldn't handle all versions on nuget.org. I need to come up with more clever solutions on how to properly encode all precedence information.

**Comment by ismcagdas** [comment]
In my scenario, I'm trying to find highest major version number for an end user so that my NuGet server will allow end user to download all minor versions of that major version. 

When I look at https://semver.org/#spec-item-11, it is obvious that it is hard to sorting 😄 . Feel free to close this issue if you want. I only need Major version number in my case and I will either add it to Package entity or I will get all records first as you suggest and apply sorting then.

Thank you for your great work again, it saved lots of time for me 👍

**Comment by loic-sharma** [comment]
> In my scenario, I'm trying to find highest major version number for an end user so that my NuGet server will allow end user to download all minor versions of that major 

Gotcha. FYI, I recently added [an SDK to interact with NuGet servers](https://github.com/loic-sharma/BaGet/tree/master/src/BaGet.Protocol#bagetprotocol). You should be able to do this with something like:

```csharp
NuGetClient client = new NuGetClient("https://my.baget.test/v3/index.json");

IReadOnlyList<NuGetVersion>> versions = await client.ListPackageVersionsAsync("Newtonsoft.Json");
if (!versions.Any())
{
    Console.WriteLine("Could not find any versions");
}

var latestMajorVersions = versions
    .Select(NuGetVersion.Parse)
    .GroupBy(v => v.Major)
    .OrderByDescending(g => g.Key)
    .First()
    .ToList();

foreach (var latestMajorVersion in latestMajorVersions)
{
    Console.WriteLine($"Found latest major version {latestMajorVersion}");
}
```

This should work on both BaGet and nuget.org.

> Thank you for your great work again, it saved lots of time for me 👍

Of course! Please let me know if you any other questions

**Comment by ismcagdas** [comment]
Thanks.
