### ISSUE TITLE
Root error

### ISSUE THREAD

**Issue by lnicolae** [loic-sharma/BaGet#420]
H:\New folder\uGet\BaGet\src\BaGet>dotnet run
C:\Users\xxx\.nuget\packages\microsoft.build.tasks.git\1.0.0-beta-63127-02\build\Microsoft.Build.Tasks.Git.targets(28,5): error MSB4044: The "Microsoft.Build.Tasks.Git.GetRepositoryUrl" task was not given a value for the required parameter "Root". [H:\New folder\uGet\BaGet\src\BaGet.Protocol\BaGet.Protocol.csproj]

The build failed. Fix the build errors and run again.

**Comment by loic-sharma** [comment]
Did you download BaGet's source code from the GitHub release? If so, this should be fixed by https://github.com/loic-sharma/BaGet/pull/434.

If not, could you send me a [binlog of your build](https://github.com/Microsoft/msbuild/blob/master/documentation/wiki/Binary-Log.md):

1. Make sure you've installed the [.NET Core SDK](https://dotnet.microsoft.com/download)
1. Navigate to BaGet
1. Build BaGet using `dotnet build /bl`
1. This will create a file named `msbuild.binlog`. Please send that to me
