### ISSUE TITLE
Cannot publish symbol package if version contains upper case characters

### ISSUE THREAD

**Issue by breigo** [loic-sharma/BaGet#472]
Cannot publish symbol package if the package version contains upper case characters in a prerelease identifier (e.g. 1.0.0-RC1).

### Steps to reproduce

1. Create package + symbols package with version Major.Minor.Patch-[Build Identifier containing upper case characters] (e.g.: 1.0.0-RC1)
`dotnet pack -c Release -o ../nuget/ -p:Version=1.0.0-RC1 -p:SymbolPackageFormat=snupkg --include-symbols`

2. Publish package:
`dotnet nuget push *.nupkg -s $BAGET_URL -k $BAGET_API_KEY`

3. Result is:
Nuget package is pushed successfully
Symbols package is NOT pushed (404)

### Expected behavior
Both packages should be pushed.

### Screenshots
Result of `dotnet nuget push`
![image](https://user-images.githubusercontent.com/1415803/74366610-9e254380-4dd0-11ea-9528-949970a252e8.png)

### Additional context
The workflow succeeds, if no uppercase characters are present (e.g. 1.0.0-rc2).

**Comment by loic-sharma** [comment]
Hi, thanks for opening this issue! It looks like you're running into the same bug as in https://github.com/loic-sharma/BaGet/issues/458, which was fixed by https://github.com/loic-sharma/BaGet/pull/466. If you're using SQLite, you will need to recreate your database and then reupload all their packages to get this fix:

1. Delete the SQLite database: `rm baget.db`
1. Run BaGet to recreate the database
1. Reupload all the packages:
    1. Navigate to your storage folder: `cd packages`
    1. Push all packages: `dotnet nuget push .\**\*.nupkg --source http://localhost:5000/v3/index.json`

Please let me know if that doesn't fix your issue or if you run into any difficulties.

**Comment by loic-sharma** [comment]
I’ll close this off given that this bug should be fixed now. Feel free to leave a comment if you need any help!
