### ISSUE TITLE
Improve validation of AppSettings/IConfiguration

### ISSUE THREAD

**Issue by WernerMairl** [loic-sharma/BaGet#48]
Currently we get a lot of ArgumentNull Exceptions on unexpected locations if we start the App (WebApp or Tests) without config Settings (appsettings.json).

Suggest:
- fail fast and early wiith better exception types and messages
- use defaults (Convention over Configuration) instead of exceptions where it is possible
- include (unit) tests.

**Comment by WernerMairl** [comment]
I have started to improve that!
Not ready for PR but input/comments are welcome!
https://github.com/WernerMairl/BaGet/tree/Config

**Comment by loic-sharma** [comment]
Your branch looks good. One comment, I think it'd be better to focus the exceptions' messages on the configs themselves rather than the config's types. For example:

`$"{typeof(MirrorOptions).Name} not defined/configured"`

A customer that's not familiar with BaGet's inner workings would have to look into the code to understand which config is missing. A better message could be:

`$"The '{nameof(options.Mirror}' configuration is missing"`

What do you think?

**Comment by loic-sharma** [comment]
This was addressed by https://github.com/loic-sharma/BaGet/pull/147
