### ISSUE TITLE
Unittesting against official Nuget v3 (core) Client

### ISSUE THREAD

**Issue by WernerMairl** [loic-sharma/BaGet#50]
In the current (first draft) of testing infrastructure we use "Microsoft.AspNetCore.TestHost.TestServer" for testing Controllers.

Idea/Requirement
Inject HttpClient capabilites provided by the TestServer into NuGet.Protocol.HttpSource and use official NuGet.Client Assemblies (V3/Core) to (unit) test our Controllers (in process).

Helpful ?
Any concerns ?

**Comment by WernerMairl** [comment]
Prototype is working - 
Challenges wit NuGet V3 Dependency Injection Model are solved.
Needs some refactoring and review before PR....

**Comment by loic-sharma** [comment]
On the NuGet team we have a few high-level “end to end” tests that use the nuget client executable to push packages, and then restore them. These ensure the core functionality works. 

We chose to not test the server using client libraries as:

1. What’s truly important is that the server respects the NuGet protocol (so that other clients like paket work as expected)
2. The client does not give guarantees for backwards compatibility of its APIs. Only the command line options are backwards compatible

I think what we should do is test that BaGet adheres to the NuGet protocol, and ensure that [NuGet’s end to end tests](https://github.com/NuGet/NuGet.Services.EndToEnd) pass for BaGet.

**Comment by loic-sharma** [comment]
Closing this off due to the discussion. Feel free to open more issues @WernerMairl! :)
