### ISSUE TITLE
Env var support missing?

### ISSUE THREAD

**Issue by ffandreassoroko** [loic-sharma/BaGet#548]
### Describe the bug
We are using the Baget docker image and noticed in the last updates, that the env var support was dropped? 

### Additional context
also its not possible to change the url/port for the container with the env `ASPNETCORE_URLS`
(before it was 80 and now it is 5000)
i think if you would support this, you could also remove your "custom" url setting 
https://github.com/loic-sharma/BaGet/blob/master/src/BaGet/Program.cs#L85

downgraded back to : 636c38146791bf7bdaa297587e196508f732cd08

`.AddEnvironmentVariables()` would be great 👍 
https://github.com/loic-sharma/BaGet/blob/master/src/BaGet/Program.cs#L82

**Comment by loic-sharma** [comment]
Thanks for reporting this! Also, thanks for the detailed bug report, it helps a lot :)

I think the easiest fix may be to revert https://github.com/loic-sharma/BaGet/pull/525 for now. I think I need to think on this a little more as it's not clear how to be solve this problem right now.

> ... before [the port] was 80 and now it is 5000

Ah this change was not intentional. Thanks for the heads up.

> also its not possible to change the url/port for the container with the env `ASPNETCORE_URLS`

This is happening because the `appsettings.json` file's `Url` config is overriding the URL provided by the `ASPNETCORE_URLS` environment variable.

**Comment by loic-sharma** [comment]
I'm working on a fix here: https://github.com/loic-sharma/BaGet/pull/549. I'll let others review this in case they have concerns, but will merge this in sometime tomorrow.

**Comment by loic-sharma** [comment]
Ok this should be fixed and a new Docker image should be created soon. Please let me know if you run into any additional issues when using the latest version of BaGet.

Please note that I recently did a massive refactoring of BaGet (https://github.com/loic-sharma/BaGet/pull/538); I tested this as thoroughly as possible but sweeping changes like this may have bugs.

**Comment by ffandreassoroko** [comment]
before we update and getting again some problems... just a little question. 

is it still possible to configure baget over env ? ( `Storage__Type`, `Database__Type` etc.. )

**Comment by loic-sharma** [comment]
Yup that should still work.
