### ISSUE TITLE
Is this project still active?

### ISSUE THREAD

**Issue by jeroenlandheer** [loic-sharma/BaGet#650]
First of all, I really like this piece of software... but it looks like it is mostly dormant right now. If we look at the code frequency there hasn't been any activity in the last couple of months, issues are open of 4+ years old and the list is growing. 

As any software that is not actively being maintained, it eventually becomes obsolete. I wonder if this is the case for BaGet, seeing others trying to fill the gap. 

We're missing some critical features (Authentication, support for the V2 API to name a few) which are still on this project's backlog for quite some time now. What are the plans going forward?

Do I need to get worried and look for something else?

**Comment by mattj23** [comment]
This is a good question; I'm wondering the same thing.  @loic-sharma seems still active on github and twitter, but it doesn't seem like he's been active on BaGet since at least the beginning of April.  PRs seem to have been sitting for a little while (I submitted #644 in April).

Are there other alternative projects that are viable at this point?  Is there someone else who knows BaGet well enough to triage a fork until Loic has more time for the project again?  I could potentially contribute some effort towards backend stuff, but I have no experience with React.

**Comment by loic-sharma** [comment]
Hi apologies for the lack of response. Work, life, and COVID all took a toll and I took some time off.

> issues are open of 4+ years old and the list is growing.

A lot of issues are questions and bug reports. To be honest, investigating these can be draining. [I've started a Discord server](https://discord.gg/MWbhpf66mk) and I'm hoping we can bootstrap a community that helps each other out to reduce my support load.

> We're missing some critical features (Authentication, support for the V2 API to name a few) which are still on this project's backlog for quite some time now. What are the plans going forward?

These are coming, but I don't have an ETA since this is a side project I do in my free time. My high-level plans in rough order are:

* Upgrade to .NET 6
* Add V2 API support
* Add HTTP basic and AAD auth
* Experiment with a plugin/extensibility model
* Increase test coverage
* Stabilize BaGet's APIs
* Release BaGet 1.0
* Join .NET Foundation

>  I could potentially contribute some effort towards backend stuff, but I have no experience with React.

Good news, the React frontend was removed :)
